apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: primuslearning-project-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
